name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 每次推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - uses: actions/checkout@v4

      # 安装 Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      # 缓存编译结果，加快下次构建速度
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 安装 trunk
      - name: Install trunk
        run: cargo install trunk

      # 编译
      - name: Build
        run: trunk build --release --public-url /Clock-leptos/

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
